#!/usr/bin/env bash
set -euo pipefail

# Phase 5.2: Tang Nano 9K target scaffold for ascon-neorv32.
# Run from the ascon-neorv32 repository root.

if [ ! -f rtl/ascon_aead128_xbus.v ]; then
  echo "ERROR: run this from the ascon-neorv32 repo root" >&2
  exit 1
fi

mkdir -p boards/tang-nano-9k/variants \
         boards/tang-nano-9k/gowin \
         boards/tang-nano-9k/constraints \
         hw/neorv32/tang-nano-9k \
         doc

cat > boards/tang-nano-9k/README.md <<'EOF'
# Tang Nano 9K target profile

This directory contains the Tang Nano 9K bring-up profile for the NEORV32 Ascon accelerator integration.

The target board is intentionally treated as a **bring-up board** first, not as the final maximum-throughput FPGA target. The first objective is to prove:

```text
NEORV32 CPU -> XBUS -> Ascon accelerator -> software known-answer test
```

## Board assumptions

Initial target:

```text
Board:       Sipeed Tang Nano 9K
FPGA:        GW1NR-LV9QN88PC6/I5
Clock:       27 MHz onboard oscillator
Capacity:    8640 LUT4-class logic units
```

## Bring-up strategy

Start small and increase the accelerator only after a full SoC build works.

Recommended order:

```text
1. accelerator-only synthesis sweep using the variants in boards/tang-nano-9k/variants/
2. minimal NEORV32 + one encryption accelerator, RPC=1
3. NEORV32 software KAT over UART
4. try RPC=2
5. only then consider RPC=4, RPC=8, or dual encrypt/decrypt hardware
```

Avoid making the first hardware build too ambitious. A dual encrypt/decrypt accelerator with RPC=8 is unlikely to be the best first target on this device.

## Variants

```text
small.mk           encrypt, RPC=1
medium.mk          encrypt, RPC=2
fast-if-fits.mk    encrypt, RPC=4
decrypt-small.mk   decrypt, RPC=1
```

Use from the repository root:

```sh
make TANG_VARIANT=small board-tangnano9k-info
make TANG_VARIANT=small synth-tangnano9k-accel
make synth-tangnano9k-matrix
```

The current synthesis targets are still generic Yosys gates for accelerator sizing. Gowin place-and-route comes after we choose the exact NEORV32 top-level and pin constraints.
EOF

cat > boards/tang-nano-9k/variants/small.mk <<'EOF'
# Tang Nano 9K conservative bring-up profile.
BOARD_NAME := tang-nano-9k
FPGA_DEVICE ?= GW1NR-LV9QN88PC6/I5
BOARD_CLOCK_HZ ?= 27000000
ACCEL_TOP := ascon_aead128_xbus
ACCEL_DECRYPT := 0
ACCEL_RPC := 1
ACCEL_PROFILE_NAME := small-encrypt-rpc1
EOF

cat > boards/tang-nano-9k/variants/medium.mk <<'EOF'
# Tang Nano 9K medium accelerator profile.
BOARD_NAME := tang-nano-9k
FPGA_DEVICE ?= GW1NR-LV9QN88PC6/I5
BOARD_CLOCK_HZ ?= 27000000
ACCEL_TOP := ascon_aead128_xbus
ACCEL_DECRYPT := 0
ACCEL_RPC := 2
ACCEL_PROFILE_NAME := medium-encrypt-rpc2
EOF

cat > boards/tang-nano-9k/variants/fast-if-fits.mk <<'EOF'
# Tang Nano 9K aggressive single-accelerator profile.
# Use only after small/medium fit with NEORV32.
BOARD_NAME := tang-nano-9k
FPGA_DEVICE ?= GW1NR-LV9QN88PC6/I5
BOARD_CLOCK_HZ ?= 27000000
ACCEL_TOP := ascon_aead128_xbus
ACCEL_DECRYPT := 0
ACCEL_RPC := 4
ACCEL_PROFILE_NAME := fast-if-fits-encrypt-rpc4
EOF

cat > boards/tang-nano-9k/variants/decrypt-small.mk <<'EOF'
# Tang Nano 9K conservative decryption profile.
BOARD_NAME := tang-nano-9k
FPGA_DEVICE ?= GW1NR-LV9QN88PC6/I5
BOARD_CLOCK_HZ ?= 27000000
ACCEL_TOP := ascon_aead128_xbus
ACCEL_DECRYPT := 1
ACCEL_RPC := 1
ACCEL_PROFILE_NAME := small-decrypt-rpc1
EOF

cat > boards/tang-nano-9k/gowin/README.md <<'EOF'
# Gowin project placeholder

This directory is reserved for the Gowin EDA project files for the Tang Nano 9K NEORV32 build.

We are not committing a generated Gowin project yet because the exact NEORV32 top-level, memory strategy, UART pins, and clock/PLL choice still need to be locked.

Expected future files:

```text
ascon_neorv32_tangnano9k.gprj
gowin_run.tcl
impl/pnr constraints generated by Gowin EDA
```

The current Phase 5.2 targets only perform accelerator-level synthesis sizing. Full Gowin place-and-route is Phase 5.3/5.4.
EOF

cat > boards/tang-nano-9k/constraints/README.md <<'EOF'
# Constraints placeholder

Do not add guessed Tang Nano 9K pin constraints here.

The first real `.cst` file should be derived from the Sipeed schematic and the chosen NEORV32 top-level pins. At minimum we will need:

```text
27 MHz clock input
UART RX/TX through the onboard USB-UART path
reset strategy
optional LEDs for heartbeat/status
JTAG kept available for programming/debug
```

Until those signals are fixed in the top-level, this directory remains documentation-only.
EOF

cat > hw/neorv32/tang-nano-9k/README.md <<'EOF'
# NEORV32 Tang Nano 9K hardware integration

This directory is the future home of the board-specific NEORV32 top-level for Tang Nano 9K.

Current Phase 5.2 scope:

```text
- define board target strategy
- define accelerator sizing variants
- keep one XBUS accelerator as the initial hardware target
- do not yet claim a complete Gowin bitstream build
```

Planned top-level structure:

```text
Tang Nano 9K pins
  -> clock/reset/UART/JTAG wiring
  -> NEORV32 top
      -> XBUS external peripheral interface
          -> ascon_aead128_xbus
```

Initial address map:

```text
0xF000_0000  Ascon accelerator MMIO window
```

For the first board build, use a single accelerator instance. Dual encrypt/decrypt windows can be reintroduced later if resource usage allows.
EOF

cat > hw/neorv32/tang-nano-9k/ascon_xbus_map.vh <<'EOF'
// SPDX-License-Identifier: Apache-2.0
// Tang Nano 9K NEORV32 Ascon accelerator address map.

`ifndef ASCON_TANG_NANO_9K_XBUS_MAP_VH
`define ASCON_TANG_NANO_9K_XBUS_MAP_VH

`define ASCON_XBUS_BASE_ADDR 32'hF000_0000
`define ASCON_XBUS_ADDR_MASK 32'hFFFF_FF00

`endif
EOF

cat > doc/phase5_2.md <<'EOF'
# Phase 5.2 — Tang Nano 9K target profile

Phase 5.2 introduces Tang Nano 9K as the first physical bring-up board.

This phase does **not** yet create a complete NEORV32 Gowin bitstream. It establishes a conservative board profile and accelerator synthesis variants so we can answer resource-fit questions before wiring the full SoC.

## Target

```text
Board: Sipeed Tang Nano 9K
FPGA:  GW1NR-LV9QN88PC6/I5
Clock: 27 MHz onboard oscillator
```

## Principle

The board is small. Therefore the first hardware build should not use the fastest or largest accelerator.

Initial profile:

```text
single accelerator instance
DECRYPT=0
ROUNDS_PER_CYCLE=1
small FIFO defaults from the core wrapper
```

After that works:

```text
try RPC=2
try RPC=4 only if there is comfortable timing/resource margin
add decryption or dual windows only if area allows
```

## Commands

```sh
make TANG_VARIANT=small board-tangnano9k-info
make TANG_VARIANT=small synth-tangnano9k-accel
make synth-tangnano9k-matrix
```

## Exit criteria

Phase 5.2 is complete when:

```text
- the board profile files are committed
- accelerator-only synthesis matrix runs
- we choose the first NEORV32 top-level configuration for Phase 5.3
```
EOF

# Append Makefile targets if not already present.
if ! grep -q 'board-tangnano9k-info' Makefile; then
cat >> Makefile <<'EOF'

# -----------------------------------------------------------------------------
# Tang Nano 9K board-profile helpers
# -----------------------------------------------------------------------------
TANG_VARIANT ?= small
TANG_VARIANT_FILE := boards/tang-nano-9k/variants/$(TANG_VARIANT).mk
-include $(TANG_VARIANT_FILE)

.PHONY: board-tangnano9k-info synth-tangnano9k-accel synth-tangnano9k-matrix

board-tangnano9k-info:
	@test -f "$(TANG_VARIANT_FILE)" || { echo "ERROR: unknown TANG_VARIANT='$(TANG_VARIANT)'"; exit 1; }
	@echo "Board:              $${BOARD_NAME:-tang-nano-9k}"
	@echo "Variant:            $(TANG_VARIANT)"
	@echo "FPGA_DEVICE:        $(FPGA_DEVICE)"
	@echo "BOARD_CLOCK_HZ:     $(BOARD_CLOCK_HZ)"
	@echo "ACCEL_TOP:          $(ACCEL_TOP)"
	@echo "ACCEL_PROFILE_NAME: $(ACCEL_PROFILE_NAME)"
	@echo "ACCEL_DECRYPT:      $(ACCEL_DECRYPT)"
	@echo "ACCEL_RPC:          $(ACCEL_RPC)"

synth-tangnano9k-accel: check-core | $(BUILD_DIR)
	@test -f "$(TANG_VARIANT_FILE)" || { echo "ERROR: unknown TANG_VARIANT='$(TANG_VARIANT)'"; exit 1; }
	$(YOSYS) -p 'read_verilog -sv $(RTL_FILES); chparam -set DECRYPT $(ACCEL_DECRYPT) ascon_aead128_xbus; chparam -set ROUNDS_PER_CYCLE $(ACCEL_RPC) ascon_aead128_xbus; synth -top ascon_aead128_xbus; stat -top ascon_aead128_xbus' > $(BUILD_DIR)/yosys_tangnano9k_$(TANG_VARIANT)_accel.txt
	cat $(BUILD_DIR)/yosys_tangnano9k_$(TANG_VARIANT)_accel.txt

synth-tangnano9k-matrix:
	$(MAKE) TANG_VARIANT=small synth-tangnano9k-accel
	$(MAKE) TANG_VARIANT=medium synth-tangnano9k-accel
	$(MAKE) TANG_VARIANT=fast-if-fits synth-tangnano9k-accel
	$(MAKE) TANG_VARIANT=decrypt-small synth-tangnano9k-accel
EOF
fi

# Update sanity script gently: ensure it allows/requires new board docs if the script is readable.
if [ -f scripts/sanity_check_tree.sh ] && ! grep -q 'boards/tang-nano-9k/README.md' scripts/sanity_check_tree.sh; then
  python3 - <<'PY'
from pathlib import Path
p = Path('scripts/sanity_check_tree.sh')
s = p.read_text()
needle = 'doc/phase4_3.md'
insert = '''doc/phase4_3.md \\
  boards/tang-nano-9k/README.md \\
  boards/tang-nano-9k/variants/small.mk \\
  boards/tang-nano-9k/variants/medium.mk \\
  boards/tang-nano-9k/variants/fast-if-fits.mk \\
  boards/tang-nano-9k/variants/decrypt-small.mk \\
  hw/neorv32/tang-nano-9k/README.md \\
  hw/neorv32/tang-nano-9k/ascon_xbus_map.vh \\
  doc/phase5_2.md'''
if needle in s:
    s = s.replace(needle, insert)
p.write_text(s)
PY
fi

echo "Phase 5.2 Tang Nano 9K scaffold applied."
echo "Run:"
echo "  ./scripts/sanity_check_tree.sh"
echo "  make TANG_VARIANT=small board-tangnano9k-info"
echo "  make TANG_VARIANT=small synth-tangnano9k-accel"
echo "  make synth-tangnano9k-matrix"
